# Generated by Django 5.1.1 on 2024-09-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0003_plato_imagen_alter_plato_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
