# Generated by Django 5.1.1 on 2024-10-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0009_alter_encuesta_plato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('categoria', models.CharField(max_length=32)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
