# Generated by Django 5.1.2 on 2024-11-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0018_alter_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
