# Generated by Django 5.1.2 on 2024-11-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0022_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Preparando', 'Preparando 🍲'), ('En entrega ⛟', 'En entrega ⛟'), ('Entregado ✅', 'Entregado ✅')], default='Preparando', max_length=50),
        ),
    ]
