# Generated by Django 5.1.1 on 2024-09-29 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0006_encuesta_opcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcion',
            name='encuesta',
        ),
        migrations.DeleteModel(
            name='Encuesta',
        ),
        migrations.DeleteModel(
            name='Opcion',
        ),
    ]
