# Generated by Django 5.1.2 on 2024-11-06 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0013_voto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_envio', models.CharField(max_length=255)),
                ('hora_entrega', models.CharField(max_length=20)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.carrito')),
            ],
        ),
    ]
