# Generated by Django 5.1.1 on 2024-09-29 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0007_remove_opcion_encuesta_delete_encuesta_delete_opcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercio.plato')),
            ],
        ),
    ]
